spring:
  application:
    name: app
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  profiles:
    active: prod

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem