spring:
  application:
    name: app
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

  profiles:
    active: prod

security:
  scrypt:
    cpu-cost: 32
    memory-cost: 2
    parallelism: 1
    key-length: 4
    salt-length: 2147

rsa:
  private-key: classpath:certificates/private.pem
  public-key: classpath:certificates/public.pem