spring:
  application:
    name: app

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always

  profiles:
    active: development

security:
  scrypt:
    cpu-cost: 1024
    memory-cost: 4
    parallelism: 1
    key-length: 16
    salt-length: 21474836